# syntax=docker/dockerfile:1

###############################################################################
# Artemis vulnerability scanner — production image
#
# Bundles the Flask/SocketIO web app, the Celery worker code, and the external
# scanning tools it shells out to (nmap, nuclei). The same image runs both the
# "web" and "worker" services in docker-compose; the entrypoint selects the role.
###############################################################################

# --- Frontend build (React/Vite) -------------------------------------------
# Emits static/ui/ which Flask serves at "/". Kept in its own stage so a
# python-only change does not reinstall node modules.
FROM node:20.18.1-slim@sha256:b2c8e0eb8a6aeeae33b2711f8f516003e27ee45804e270468d937b3214f2f0cc AS frontend
WORKDIR /build/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build
# -> /build/static/ui  (vite base '/static/ui/', outDir '../static/ui')

FROM python:3.14.7-slim-bookworm@sha256:9ab8d9c8514b44f90cf0029dd42fdd7e9e211e639c8b995304cc04568dee900f

# --- External scanning tools --------------------------------------------------
# nmap  : service/port discovery (python-nmap shells out to it)
# nuclei : template-based vulnerability scanning
# Pinned by default; override with --build-arg NUCLEI_VERSION= for latest.
ARG NUCLEI_VERSION=3.11.1

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    MPLCONFIGDIR=/tmp/matplotlib \
    FLASK_APP=run.py \
    # Top-level scanner modules (device_type, nvd_feeds, fingerprint/, ...) are
    # not part of the installed `artemis` package. gunicorn adds CWD to sys.path
    # but the Celery prefork pool does not — pin it so every process can import.
    PYTHONPATH=/app

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        nmap \
        ca-certificates \
        curl \
        unzip \
        tini \
        libpq5 \
        libxml2 \
        libxslt1.1 \
        libmagic1 \
        postgresql-client \
        # WeasyPrint (PDF report export) — Pango text stack + base fonts
        libpango-1.0-0 \
        libpangoft2-1.0-0 \
        libjpeg62-turbo \
        libffi8 \
        shared-mime-info \
        fonts-dejavu-core; \
    rm -rf /var/lib/apt/lists/*

# Install nuclei from GitHub releases. When NUCLEI_VERSION is empty the latest
# release is resolved at build time.
RUN set -eux; \
    arch="$(dpkg --print-architecture)"; \
    case "$arch" in \
        amd64) nuclei_arch=amd64 ;; \
        arm64) nuclei_arch=arm64 ;; \
        *) echo "unsupported arch: $arch" >&2; exit 1 ;; \
    esac; \
    version="${NUCLEI_VERSION}"; \
    if [ -z "$version" ]; then \
        version="$(curl -fsSL https://api.github.com/repos/projectdiscovery/nuclei/releases/latest \
            | grep -m1 '"tag_name"' | sed -E 's/.*"v?([^"]+)".*/\1/')"; \
    fi; \
    version="${version#v}"; \
    url="https://github.com/projectdiscovery/nuclei/releases/download/v${version}/nuclei_${version}_linux_${nuclei_arch}.zip"; \
    echo "Downloading $url"; \
    curl -fsSL -o /tmp/nuclei.zip "$url"; \
    unzip -o /tmp/nuclei.zip -d /usr/local/bin nuclei; \
    rm /tmp/nuclei.zip; \
    chmod +x /usr/local/bin/nuclei; \
    nuclei -version

WORKDIR /app

# --- Python dependencies -----------------------------------------------------
# Install the fully pinned, hashed runtime from the lock file. pyproject.toml is
# the human-edited source; requirements.lock is generated by scripts/lock-deps.sh
# and covers the postgres + wsgi + fingerprint extras. Layered before the app
# code so it stays cached across application changes.
COPY pyproject.toml requirements.lock ./
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends build-essential; \
    pip install --no-cache-dir --require-hashes -r requirements.lock; \
    apt-get purge -y --auto-remove build-essential; \
    rm -rf /var/lib/apt/lists/*

# --- Application code -------------------------------------------------------
COPY . .
# Built SPA from the frontend stage (host static/ui/ is .dockerignore'd).
COPY --from=frontend /build/static/ui ./static/ui
# Register the local package only; every third-party dep is already pinned above.
RUN pip install --no-cache-dir --no-deps -e .

# Persistent data (legacy sqlite NVD/CPE cache) and nuclei templates.
RUN mkdir -p /data /root/nuclei-templates /root/.config/nuclei

EXPOSE 5005

ENTRYPOINT ["tini", "--", "/app/docker/entrypoint.sh"]
CMD ["web"]
