"""tier 1 baseline schema

Revision ID: 6766db20a99d
Revises: 
Create Date: 2026-09-02 07:12:18.281490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6766db20a99d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('packages_count', sa.Integer(), nullable=True),
    sa.Column('ports_count', sa.Integer(), nullable=True),
    sa.Column('vulns_matched', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('mac_address', sa.Text(), nullable=True),
    sa.Column('os_info_json', sa.Text(), nullable=True),
    sa.Column('last_checkin', sa.Text(), nullable=True),
    sa.Column('checkin_interval', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('agent_version', sa.Text(), nullable=True),
    sa.Column('system_info_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_key')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('last_used', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_os_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('distro', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('kernel', sa.Text(), nullable=True),
    sa.Column('arch', sa.Text(), nullable=True),
    sa.Column('os_family', sa.Text(), nullable=True),
    sa.Column('os_id', sa.Text(), nullable=True),
    sa.Column('pretty_name', sa.Text(), nullable=True),
    sa.Column('scan_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('reverse_dns', sa.Text(), nullable=True),
    sa.Column('aliases_json', sa.Text(), nullable=True),
    sa.Column('os_name', sa.Text(), nullable=True),
    sa.Column('os_family', sa.Text(), nullable=True),
    sa.Column('os_vendor', sa.Text(), nullable=True),
    sa.Column('os_accuracy', sa.Text(), nullable=True),
    sa.Column('device_type', sa.Text(), nullable=True),
    sa.Column('mac_address', sa.Text(), nullable=True),
    sa.Column('mac_vendor', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.Text(), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cred_type', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('key_path', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cve_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('cve_id', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_cpe', sa.Text(), nullable=True),
    sa.Column('has_exploit', sa.Integer(), nullable=True),
    sa.Column('exploit_ids', sa.Text(), nullable=True),
    sa.Column('exploit_url', sa.Text(), nullable=True),
    sa.Column('scan_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'cve_id', name='uq_cve_match_ip_cve')
    )
    with op.batch_alter_table('cve_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cve_matches_ip'), ['ip'], unique=False)

    op.create_table('fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('signature_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('vendor', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('cpe', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('tls_subject_cn', sa.Text(), nullable=True),
    sa.Column('tls_subject_org', sa.Text(), nullable=True),
    sa.Column('tls_issuer_org', sa.Text(), nullable=True),
    sa.Column('tls_self_signed', sa.Integer(), nullable=True),
    sa.Column('http_title', sa.Text(), nullable=True),
    sa.Column('http_server', sa.Text(), nullable=True),
    sa.Column('favicon_hash', sa.Integer(), nullable=True),
    sa.Column('scan_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'port', 'protocol', 'signature_id', name='uq_fp_ip_port_proto_sig')
    )
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprints_ip'), ['ip'], unique=False)

    op.create_table('installed_software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('package_name', sa.Text(), nullable=True),
    sa.Column('package_version', sa.Text(), nullable=True),
    sa.Column('cpe', sa.Text(), nullable=True),
    sa.Column('scan_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'package_name', name='uq_sw_ip_pkg')
    )
    with op.batch_alter_table('installed_software', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installed_software_ip'), ['ip'], unique=False)

    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_scan_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('scan_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('hosts_scanned', sa.Integer(), nullable=True),
    sa.Column('ports_found', sa.Integer(), nullable=True),
    sa.Column('vulns_found', sa.Integer(), nullable=True),
    sa.Column('new_vulns', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('cancel_requested_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_task_id'), ['task_id'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('scan_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_ip'), ['ip'], unique=False)

    op.create_table('scheduled_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('scan_type', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.Text(), nullable=False),
    sa.Column('cron_expression', sa.Text(), nullable=True),
    sa.Column('schedule_hour', sa.Integer(), nullable=True),
    sa.Column('schedule_minute', sa.Integer(), nullable=True),
    sa.Column('schedule_day_of_week', sa.Integer(), nullable=True),
    sa.Column('schedule_day_of_month', sa.Integer(), nullable=True),
    sa.Column('scan_options_json', sa.Text(), nullable=True),
    sa.Column('credential_ids_json', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('last_run', sa.Text(), nullable=True),
    sa.Column('next_run', sa.Text(), nullable=True),
    sa.Column('last_status', sa.Text(), nullable=True),
    sa.Column('last_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('notify_on_complete', sa.Integer(), nullable=True),
    sa.Column('notify_on_new_vulns', sa.Integer(), nullable=True),
    sa.Column('compare_with_previous', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('site_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('targets_total', sa.Integer(), nullable=True),
    sa.Column('targets_scanned', sa.Integer(), nullable=True),
    sa.Column('targets_failed', sa.Integer(), nullable=True),
    sa.Column('ports_found', sa.Integer(), nullable=True),
    sa.Column('vulns_found', sa.Integer(), nullable=True),
    sa.Column('new_vulns', sa.Integer(), nullable=True),
    sa.Column('removed_vulns', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_scans_site_id'), ['site_id'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('targets_json', sa.Text(), nullable=True),
    sa.Column('excluded_targets_json', sa.Text(), nullable=True),
    sa.Column('scan_type', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.Text(), nullable=True),
    sa.Column('scan_options_json', sa.Text(), nullable=True),
    sa.Column('credential_ids_json', sa.Text(), nullable=True),
    sa.Column('schedule_enabled', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.Text(), nullable=True),
    sa.Column('schedule_hour', sa.Integer(), nullable=True),
    sa.Column('schedule_minute', sa.Integer(), nullable=True),
    sa.Column('schedule_day_of_week', sa.Integer(), nullable=True),
    sa.Column('schedule_day_of_month', sa.Integer(), nullable=True),
    sa.Column('next_run', sa.Text(), nullable=True),
    sa.Column('last_run', sa.Text(), nullable=True),
    sa.Column('last_status', sa.Text(), nullable=True),
    sa.Column('last_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notify_on_complete', sa.Integer(), nullable=True),
    sa.Column('notify_on_new_vulns', sa.Integer(), nullable=True),
    sa.Column('compare_with_previous', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('last_login', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('vuln_id', sa.Text(), nullable=True),
    sa.Column('vuln_name', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.Text(), nullable=True),
    sa.Column('cwe_id', sa.Text(), nullable=True),
    sa.Column('references_json', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Text(), nullable=True),
    sa.Column('scan_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'port', 'protocol', 'vuln_id', name='uq_vuln_ip_port_proto_id')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerabilities_ip'), ['ip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_ip'))

    op.drop_table('vulnerabilities')
    op.drop_table('users')
    op.drop_table('sites')
    with op.batch_alter_table('site_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_scans_site_id'))

    op.drop_table('site_scans')
    op.drop_table('settings')
    op.drop_table('scheduled_scans')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_ip'))

    op.drop_table('scans')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_jobs_task_id'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_site_id'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_requested_by'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_job_type'))

    op.drop_table('scan_jobs')
    op.drop_table('scan_history')
    with op.batch_alter_table('installed_software', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installed_software_ip'))

    op.drop_table('installed_software')
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprints_ip'))

    op.drop_table('fingerprints')
    with op.batch_alter_table('cve_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cve_matches_ip'))

    op.drop_table('cve_matches')
    op.drop_table('credentials')
    op.drop_table('assets')
    op.drop_table('asset_os_details')
    op.drop_table('api_keys')
    op.drop_table('agents')
    op.drop_table('agent_reports')
    # ### end Alembic commands ###
