"""agent_data, drop legacy sqlite app-table init

Revision ID: c9c688d7ee35
Revises: b7d930a42f11
Create Date: 2026-09-02 20:41:37.055725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c688d7ee35'
down_revision = 'b7d930a42f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('packages_json', sa.Text(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('system_info_json', sa.Text(), nullable=True),
    sa.Column('os_info_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_data_ip'), ['ip'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_data_ip'))

    op.drop_table('agent_data')
    # ### end Alembic commands ###
